# Generated by Django 4.0.1 on 2022-11-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_skill_options_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.ManyToManyField(to='vacancies.Skill'),
        ),
    ]
